Improve pre-commit hook
* Check for existence of needed programs at the beginning instead of
  every iteration of the file loop
* Removed option --fail-on-warnings from puppet-lint check
* Fixed bug which ended the hook run when an empty file was committed

diff --git a/pre-commit-hook b/pre-commit-hook
--- a/pre-commit-hook
+++ b/pre-commit-hook
@@ -4,6 +4,7 @@
 #
 #    Puppet >= 2.7 is installed on this machine
 #    puppet-lint is installed on this machine
+#    ERB is installed on this machine
 #    Adjust LINTFLAGS as appropriate
 
 # Redirect output to stderr.
@@ -12,11 +13,19 @@ exec 1>&2
 TMPFILE=$(mktemp)
 STATUS=0
 
+# Register exit trap for removing temporary files
 trap 'rm -rf $TMPFILE' EXIT INT HUP
 
-IFS="
-"
+# Check for Puppet binary
+which puppet >/dev/null 2>&1 || exit 1
 
+# Check for puppet-lint
+which puppet-lint >/dev/null 2>&1 || exit 1
+
+# Check for erb
+which erb >/dev/null 2>&1 || exit 1
+
+# Get correct git revision
 if git rev-parse --quiet --verify HEAD > /dev/null
 then
     revision=HEAD
@@ -25,55 +34,49 @@ else
     revision=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
-# get a list of files changed in this transaction
+IFS="
+"
+
+# Get a list of files changed in this transaction
 declare -a FILES
 FILES=$(git diff --cached --name-only --diff-filter=ACM "${revision}")
 
 for file in ${FILES[@]}
 do
-
     # Don't check empty files
-    if [ $(git cat-file -s ":0:${file}") -eq 0 ] ; then
-        exit $STATUS
+    if [[ $(git cat-file -s ":0:${file}") -eq 0 ]]; then
+        continue
     fi
 
     extension="${file##*.}"
     git cat-file blob ":0:${file}" > $TMPFILE
-    if [ $? -ne 0 ] ; then
-        echo "Unable to checkout $file" >&2
+
+    if [[ $? -ne 0 ]]; then
+        echo "Unable to checkout ${file}"
         STATUS=2
     else
-        case "$extension" in
+        case $extension in
             pp)
-		# check for Puppet binary
-		which puppet >/dev/null 2>&1 || exit $STATUS
-
-                # puppet syntax check
+                # Puppet syntax check
                 puppet parser validate $TMPFILE >/dev/null 2>&1
-                if [ $? -ne 0 ] ; then
+                if [[ $? -ne 0 ]]; then
                     echo "Puppet syntax error in ${file}. Run 'puppet parser validate ${file}'" >&2
                     STATUS=2
                 fi
 
-		# check for puppet-lint
-		which puppet-lint >/dev/null 2>&1 || exit $STATUS
-
-                # puppet-lint check the manifest
-                puppet-lint --fail-on-warnings --with-filename --log-format "${file}:%{linenumber} %{KIND} - %{message}" $TMPFILE 2> /dev/null
-                if [ $? -ne 0 ] ; then
+                # puppet-lint check
+                puppet-lint --with-filename --log-format "${file}:%{linenumber} %{KIND} - %{message}" $TMPFILE 2> /dev/null
+                if [[ $? -ne 0 ]] ; then
                     STATUS=2
                 fi
             ;;
     
             erb)
-		# check for erb
-		which erb >/dev/null 2>&1 || exit $STATUS
-
                 # syntax check templates - this doesn't catch a lot of mistakes,
                 # but it should catch gross mistakes
-                erb -x -T - "$TMPFILE" | ruby -c > /dev/null 2>&1
-                if [ $? -ne 0 ] ; then
-                    echo "ERB syntax error in $file" >&2
+                erb -x -T - "${TMPFILE}" | ruby -c > /dev/null 2>&1
+                if [[ $? -ne 0 ]]; then
+                    echo "ERB syntax error in ${file}" >&2
                     STATUS=2
                 fi
             ;;
