added support for r10k puppetfile syntax check

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -7,6 +7,7 @@
 #    * Ruby with ERB and YAML support
 #    * Puppet >= 2.7
 #    * puppet-lint
+#    * r10k
 #
 #    Adjust LINTFLAGS as appropriate
 
@@ -16,10 +17,11 @@ exec 1>&2
 PUPPETLINT_FLAGS=${PUPPETLINT_FLAGS:-'--no-autoloader_layout-check --no-80chars-check'}
 TMPDIR=${TMPDIR:-'/tmp'}
 TMPFILE=$(mktemp "${TMPDIR}"/tmp.XXXXXXXXXX)
+TMPR10K=$(mktemp -d "${TMPDIR}"/tmp.XXXXXXXXXX)
 STATUS=0
 
 # Register exit trap for removing temporary files
-trap 'rm -rf $TMPFILE' EXIT INT HUP
+trap 'rm -rf $TMPFILE $TMPR10K' EXIT INT HUP
 
 # Check for ruby binary
 which ruby >/dev/null 2>&1 || exit 1
@@ -32,6 +34,9 @@ which puppet-lint >/dev/null 2>&1 || exit 1
 
 # Check for erb
 which erb >/dev/null 2>&1 || exit 1
+
+# Check for erb
+which r10k >/dev/null 2>&1 || exit 1
 
 # Get correct git revision
 if git rev-parse --quiet --verify HEAD > /dev/null
@@ -108,6 +113,16 @@ do
                 fi
             ;;
         esac
+        # r10k Puppetfile syntax
+        if [ "`basename $file`" == 'Puppetfile' ]; then
+            cp "${TMPFILE}" "${TMPR10K}/Puppetfile"
+            ( cd "${TMPR10K}" && r10k puppetfile check ) 2> "${TMPFILE}"
+            if [[ $? -ne 0 ]]; then
+                echo "r10k syntax error in ${file}" >&2
+                sed "s,${TMPR10K}/Puppetfile,${file}," >&2 < "${TMPFILE}"
+                STATUS=2
+            fi
+        fi
     fi
 done
 
